"""
Standalone RAG Application Exporter
Bundles generated RAG application into a self-contained, portable Python package or ZIP archive.
"""

import os
import shutil
import zipfile
import json
from typing import Optional
import numpy as np
from rag_generator.core.instance import RAGApplicationInstance


STANDALONE_RUNNER_TEMPLATE = '''"""
Standalone Generated RAG Application
Auto-generated by RAG Generator
"""

import os
import sys
import json
import argparse
import numpy as np
import re

# Load configuration and chunks
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
with open(os.path.join(CURRENT_DIR, "config.json"), "r", encoding="utf-8") as f:
    CONFIG = json.load(f)

with open(os.path.join(CURRENT_DIR, "chunks.json"), "r", encoding="utf-8") as f:
    CHUNKS = json.load(f)

VECTORS_PATH = os.path.join(CURRENT_DIR, "vectors.npy")
VECTORS = np.load(VECTORS_PATH) if os.path.exists(VECTORS_PATH) else None

def tokenize(text):
    return re.findall(r"\\b[a-z0-9_-]+\\b", text.lower())

def search(query, top_k=4):
    q_tokens = set(tokenize(query))
    scored = []
    
    for idx, c in enumerate(CHUNKS):
        content = c.get("content", "")
        c_tokens = tokenize(content)
        # Lexical overlap
        overlap = len(q_tokens.intersection(set(c_tokens)))
        score = overlap / max(1, len(q_tokens))
        if score > 0:
            scored.append((c, score))
            
    scored.sort(key=lambda x: x[1], reverse=True)
    return scored[:top_k]

def answer_query(query):
    results = search(query)
    if not results:
        return "No sufficient information found in the documents."
    
    print(f"\\n--- Query: {query} ---")
    print(f"Retrieved {len(results)} relevant chunks:\\n")
    for idx, (chunk, score) in enumerate(results, 1):
        print(f"[{idx}] Source: {chunk.get('source_name')} (Page {chunk.get('page_number', 1)}) (Score: {score:.2f})")
        print(f"    Excerpt: {chunk.get('content')[:180]}...\\n")

def main():
    parser = argparse.ArgumentParser(description=f"Standalone RAG App: {CONFIG.get('name')}")
    parser.add_argument("query", nargs="?", help="Question to ask")
    parser.add_argument("--interactive", "-i", action="store_true", help="Interactive Q&A loop")
    args = parser.parse_args()

    print(f"=== {CONFIG.get('name')} ===")
    print(f"Description: {CONFIG.get('description')}")
    print(f"Indexed Chunks: {len(CHUNKS)}\\n")

    if args.interactive or not args.query:
        print("Interactive Mode. Type your question (or 'exit' to quit):")
        while True:
            try:
                q = input("\\nQuestion > ").strip()
                if q.lower() in ("exit", "quit", "q"):
                    break
                if q:
                    answer_query(q)
            except (KeyboardInterrupt, EOFError):
                break
    else:
        answer_query(args.query)

if __name__ == "__main__":
    main()
'''


class AppExporter:
    """Exports a generated RAG Application to a standalone deployable package."""

    @staticmethod
    def export_standalone_bundle(
        instance: RAGApplicationInstance,
        output_dir: str,
        create_zip: bool = True,
    ) -> str:
        """
        Export application files, models, and runner script.
        Returns the path to the exported directory or ZIP archive.
        """
        app_export_dir = os.path.join(output_dir, f"{instance.app_id}_standalone")
        os.makedirs(app_export_dir, exist_ok=True)

        # 1. Save config and chunks
        config_path = os.path.join(app_export_dir, "config.json")
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(instance.config.model_dump_json(indent=2))

        chunks_path = os.path.join(app_export_dir, "chunks.json")
        with open(chunks_path, "w", encoding="utf-8") as f:
            json.dump([c.to_dict() for c in instance.vector_store.chunks], f, indent=2)

        # 2. Save vectors
        vectors_path = os.path.join(app_export_dir, "vectors.npy")
        if instance.vector_store.vectors is not None:
            np.save(vectors_path, instance.vector_store.vectors)

        # 3. Save standalone runner script
        runner_path = os.path.join(app_export_dir, "run_rag.py")
        with open(runner_path, "w", encoding="utf-8") as f:
            f.write(STANDALONE_RUNNER_TEMPLATE)

        # 4. Save README
        readme_path = os.path.join(app_export_dir, "README.md")
        readme_content = f"""# {instance.config.name} (Standalone RAG Application)

This is a self-contained, standalone RAG application generated by the **RAG Generator**.

## Quick Start
Run interactive queries:
```bash
python run_rag.py --interactive
```

Or query directly from the command line:
```bash
python run_rag.py "What is the primary policy regarding data retention?"
```

## Summary
- **App ID**: `{instance.app_id}`
- **Total Chunks**: `{len(instance.vector_store.chunks)}`
- **Embedding Model**: `{instance.config.embedding_model}`
- **Default LLM Provider**: `{instance.config.llm_provider}`
"""
        with open(readme_path, "w", encoding="utf-8") as f:
            f.write(readme_content)

        if not create_zip:
            return app_export_dir

        # 5. Create ZIP archive
        zip_path = os.path.join(output_dir, f"{instance.app_id}_standalone.zip")
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            for root, _, files in os.walk(app_export_dir):
                for file in files:
                    file_p = os.path.join(root, file)
                    arcname = os.path.relpath(file_p, app_export_dir)
                    zipf.write(file_p, arcname)

        return zip_path
